export enum ProductCategory {
    ELECTRONICS = 'Electrónica',
    FASHION = 'Ropa y moda',
    HOME_AND_GARDEN = 'Hogar y jardín',
    TOYS_AND_GAMES = 'Juguetes y juegos',
    SPORTS_AND_OUTDOORS = 'Deportes y actividades al aire libre',
    AUTOMOTIVE = 'Automotriz',
    BEAUTY_AND_PERSONAL_CARE = 'Belleza y cuidado personal',
    BOOKS_AND_MEDIA = 'Libros y medios',
    FOOD_AND_BEVERAGES = 'Alimentos y bebidas',
    HOME_APPLIANCES = 'Electrónicos para el hogar',
    HEALTH_AND_WELLNESS = 'Salud y bienestar',
    JEWELRY_AND_ACCESSORIES = 'Joyería y accesorios',
    HOME_FURNITURE_AND_DECOR = 'Muebles y decoración del hogar',
    TOOLS_AND_HOME_IMPROVEMENT = 'Herramientas y mejoras para el hogar',
    PET_SUPPLIES = 'Equipamiento para mascotas',
    ART_AND_CRAFTS = 'Arte y artesanía',
    OFFICE_SUPPLIES = 'Suministros de oficina y papelería',
    SPORTING_GOODS = 'Equipamiento deportivo',
    MUSICAL_INSTRUMENTS = 'Instrumentos musicales',
    TRAVEL_AND_ACCESSORIES = 'Viajes y accesorios',
  }